name: Setup React Native App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-rn-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cleanup
      run: |
        shopt -s extglob
        rm -rf !(.github)

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use the version of Node.js you prefer

    - name: Install bun
      run: npm install -g bun
      
    - name: Create React Native app
      run: bun create expo my-app

    - name: Move app to root
      run: |
        shopt -s dotglob
        mv my-app/* .
        rmdir my-app

    - name: Install tailwind
      run: |
        bun install nativewind
        bun install -d tailwindcss@3.3.2
        bunx tailwindcss init

    - name: Setup tailwind
      run: |
        bunx @tisf/regex https://raw.githubusercontent.com/t-i-f/regex/main/expo/nativewind/tailwind-config.yml
        bunx @tisf/regex https://raw.githubusercontent.com/t-i-f/regex/main/expo/nativewind/babel-config.yml

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Set up React Native app with create-expo-app'

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
